server:
  port: 1500
  tomcat:
    uri-encoding: utf-8
  context-path: /eclient
spring:
  application:
    # 微服务名称
    name: eureka-client
eureka:
  client:
    serviceUrl:
      # 注册中心地址。集群环境用逗号分隔
      defaultZone: http://10.0.11.89:1001/es/eureka/