server:
  port: 1510
  tomcat:
    uri-encoding: utf-8
  context-path: /econsumer
spring:
  application:
    # 微服务名称
    name: eureka-consumer
eureka:
  client:
    serviceUrl:
      # 服务注册中心地址，集群环境用逗号分隔
      defaultZone: http://10.0.11.89:1001/es/eureka/
