########################
# 开发环境配置
########################
server:
  port: 5080

#自定义属性
com:
  shawn:
    LearningAlways:
      text: 配置文件中生成的随机数是：
      number: ${random.int(20)} #20以内的随即数
      desc: ${com.shawn.LearningAlways.text} ${com.shawn.LearningAlways.number} #参数间的引用

spring:
    output:
      ansi:
        enabled: detect #检查终端是否支持ANSI，是的话就采用彩色输出 todo:改变配置并未生效

#日志配置
logging:
  level:
   com.shawn.LearningAlways: debug


