########################
# 通用内容配置
########################
server:
  tomcat:
    uri-encoding: utf-8
  context-path: /learningAlways

spring:
    profiles:
      # 开发环境为dev，测试环境为test
      active: dev
    output:
      ansi:
        # 检查终端是否支持ANSI，是的话就采用彩色输出 todo:改变配置并未生效
        enabled: detect

mybatis:
  type-aliases-package: com.shawn.learningalways.*.model

context:
    # 监听器
    listener:
        classes: com.shawn.learningalways.base.listener.ApplicationEventListener
