########################
# 开发环境配置
########################
server:
  port: 5001


spring:
    datasource:
      # oracle配置
      name: oracle
      url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.0.11.235)(PORT = 1521)) )(CONNECT_DATA =(SERVICE_NAME = IPCC)))
      username: zh_236
      password: 123456
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: oracle.jdbc.driver.OracleDriver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

      # mysql配置
#      name: mysql
#      url: jdbc:mysql://10.0.10.243:3306/webchat
#      username: root
#      password: utry1234
#      # 使用druid数据源
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.jdbc.Driver
#      filters: stat
#      maxActive: 20
#      initialSize: 1
#      maxWait: 60000
#      minIdle: 1
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'from dual
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20

    redis:
      # redis单机版配置
      host: 10.0.10.238
      port: 6379
      password: 123456
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
      timeout: 0

      # redis主从版配置
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 300
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#        # 连接池中的最大空闲连接
#        max-idle: 20
#        # 连接池中的最小空闲连接
#        min-idle: 20
#      # 连接超时时间（毫秒）
#      timeout: 60000
#      sentinel:
#        # 哨兵监听的reids server的名称
#        master: mymaster
#        # 哨兵的配置列表
#        nodes: 10.0.12.33:26379,10.0.12.34:26379
#      # 主从节点均为此密码，对应redis配置文件中的masterauth
#      password: 123456


mybatis:
  # mapperLocations指的路径是src/main/resources
  mapper-locations: classpath:mapper/${spring.datasource.name}/*/*Mapper.xml


#日志配置
logging:
  level:
   com.shawn.learningalways: debug


#自定义属性
com:
  shawn:
    LearningAlways:
      text: 配置文件中生成的随机数是：
      number: ${random.int(20)} #20以内的随即数
      desc: ${com.shawn.LearningAlways.text} ${com.shawn.LearningAlways.number} #参数间的引用
